inherit_from:
  - https://ctx.sh/ruby-style-guide/rubocop.yml

AllCops:
  Exclude:
  - spec/**/*
  - vendor/**/*
  - '*.gemspec'
  DisabledByDefault: true
  StyleGuideBaseURL: https://ctx.sh/ruby-style-guide/
